#if !canImport(ObjectiveC)
import XCTest

extension DecodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DecodeTests = [
        ("testAND", testAND),
        ("testMRMOVQ", testMRMOVQ),
        ("testPOPQ", testPOPQ),
        ("testPUSHQ", testPUSHQ),
    ]
}

extension ExecuteTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExecuteTests = [
        ("testADD", testADD),
        ("testAND", testAND),
        ("testMRMOVQ", testMRMOVQ),
        ("testPOPQ", testPOPQ),
        ("testPUSHQ", testPUSHQ),
        ("testSUB1", testSUB1),
        ("testSUB2", testSUB2),
    ]
}

extension FetchTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FetchTests = [
        ("testAND", testAND),
        ("testInvalid", testInvalid),
        ("testJNE", testJNE),
        ("testNOP", testNOP),
        ("testRMMOVQ", testRMMOVQ),
    ]
}

extension MemoryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MemoryTests = [
        ("testAND", testAND),
        ("testHALT", testHALT),
        ("testPOPQ", testPOPQ),
        ("testPUSHQ", testPUSHQ),
    ]
}

extension RegressionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RegressionTests = [
        ("testISA", testISA),
        ("testRegression", testRegression),
    ]
}

extension YisTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__YisTests = [
        ("testHello", testHello),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DecodeTests.__allTests__DecodeTests),
        testCase(ExecuteTests.__allTests__ExecuteTests),
        testCase(FetchTests.__allTests__FetchTests),
        testCase(MemoryTests.__allTests__MemoryTests),
        testCase(RegressionTests.__allTests__RegressionTests),
        testCase(YisTests.__allTests__YisTests),
    ]
}
#endif
