#if !canImport(ObjectiveC)
import XCTest

extension RegressionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RegressionTests = [
        ("testISA", testISA),
        ("testRegression", testRegression),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RegressionTests.__allTests__RegressionTests),
    ]
}
#endif
