name: Simulator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -c release
    - name: Run Simulator
      run: swift run -c release Simulator
    - name: Run Y86_64
      run: swift run -c release Y86_64
