name: Y86-64Seq

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test Y86_64Seq
      run: swift test --filter Y86_64SeqTests
